runtime: java
env: flex
runtime_config:
  operating_system: ubuntu22
  runtime_version: 17
handlers:
  - url: /.*
    script: this field is required, but ignored
manual_scaling:
  instances: 1
env_variables:
  MONGODB_URL: 'mongodb+srv://admin:admin@testcluster001.k7eoz0q.mongodb.net/super_shine_tx_db'
  MONGODB_COLLECTION: 'super_shine_tx_db'