steps:
  - name: maven:3.8.3-openjdk-17
    entrypoint: mvn
    args: ['clean',
           'package',
           '-Dmaven.test.skip=true',
           'sonar:sonar',
           '-Dsonar.host.url=https://sonarcloud.io',
           '-Dsonar.token=2d39390f668759ec998fd235aee32d894c74f4e0',
           '-Dsonar.projectKey=hashcode-dev',
           '-Dsonar.organization=hashcode-dev',
           'appengine:deploy']
options:
  logging: CLOUD_LOGGING_ONLY
artifacts:
    mavenArtifacts:
      - repository: 'https://asia-maven.pkg.dev/super-shine-microservice/supsershinemvnrepo'
        path: '/workspace/target/mediaresource-0.0.1-SNAPSHOT.jar'
        artifactId: 'mediaresource'
        groupId: 'org.supershine'
        version: '0.0.1-SNAPSHOT'