steps:
  - name: maven:3.8.3-openjdk-17
    entrypoint: mvn
    args: ['clean',
           'package',
           '-Dmaven.test.skip=true',
           'sonar:sonar',
           '-Dsonar.host.url=https://sonarcloud.io',
           '-Dsonar.token=${_SONAR_QUBE_TOKEN}',
           '-Dsonar.projectKey=${_SONAR_QUBE_ORG_KEY}',
           '-Dsonar.organization=${_SONAR_QUBE_ORG_ID}']
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
artifacts:
    mavenArtifacts:
      - repository: 'https://asia-maven.pkg.dev/super-shine-microservice/supsershinemvnrepo'
        path: '/workspace/target/mediaresource-0.0.1-SNAPSHOT.jar'
        artifactId: 'mediaresource'
        groupId: 'org.supershine'
        version: '0.0.1-SNAPSHOT'