steps:
  - name: maven:3.8.3-openjdk-17
    entrypoint: mvn
    args: ['package', '-Dmaven.test.skip=true']
artifacts:
    mavenArtifacts:
      - repository: 'https://asia-east1-maven.pkg.dev/super-shine-microservice/supsershinemvnrepo'
        path: '/workspace/target/mediaresource-0.0.1-SNAPSHOT.jar.original'
        artifactId: 'mediaresource'
        groupId: 'org.supershine'
        version: '0.0.1-SNAPSHOT'