substitutions:
  _SCANNER_CLI_VERSION: '4.6.0.2311'
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "SONARQUBE_SCANNER_CLI_VERSION=$_SCANNER_CLI_VERSION"
      - "-t"
      - "gcr.io/$PROJECT_ID/sonar-scanner:latest"
      - "-t"
      - "gcr.io/$PROJECT_ID/sonar-scanner:$_SCANNER_CLI_VERSION"
      - "."
  - name: maven:3.8.3-openjdk-17
    entrypoint: mvn
    args: ['package', '-Dmaven.test.skip=true']
artifacts:
    mavenArtifacts:
      - repository: 'https://asia-maven.pkg.dev/super-shine-microservice/supsershinemvnrepo'
        path: '/workspace/target/mediaresource-0.0.1-SNAPSHOT.jar'
        artifactId: 'mediaresource'
        groupId: 'org.supershine'
        version: '0.0.1-SNAPSHOT'