steps:
  - name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
    args:
          - '-Dsonar.host.url=https://sonarcloud.io'
          - '-Dsonar.login={hashcode-dev@github}'
          - '-Dsonar.projectKey={hashcode-dev}'
          - '-Dsonar.organization={hashcode-dev}'
          - '-Dsonar.sources=.'
    tags: [ 'cloud-builders-community' ]
  - name: maven:3.8.3-openjdk-17
    entrypoint: mvn
    args: ['package', '-Dmaven.test.skip=true']
artifacts:
    mavenArtifacts:
      - repository: 'https://asia-maven.pkg.dev/super-shine-microservice/supsershinemvnrepo'
        path: '/workspace/target/mediaresource-0.0.1-SNAPSHOT.jar'
        artifactId: 'mediaresource'
        groupId: 'org.supershine'
        version: '0.0.1-SNAPSHOT'