steps:
  - name: maven:3.8.3-openjdk-17
    entrypoint: mvn
    substitutions:
      - 'MONGO_DB_URL=&{_MONGO_DB_URL}'
      - 'MONGO_DB_COLLECTION_NAME=&{_MONGO_DB_COLLECTION_NAME}'
    args: ['clean',
           'package',
           '-Dmaven.test.skip=true',
           'sonar:sonar',
           '-Dsonar.host.url=${_SONAR_QUBE_HOST}',
           '-Dsonar.token=${_SONAR_QUBE_TOKEN}',
           '-Dsonar.projectKey=${_SONAR_QUBE_ORG_KEY}',
           '-Dsonar.organization=${_SONAR_QUBE_ORG_ID}']
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
artifacts:
    mavenArtifacts:
      - repository: '${_ARTIFACTORY_REPO_URL}'
        path: '${_ARTIFACTORY_REPO_PATH}'
        artifactId: '${_ARTIFACTORY_ID}'
        groupId: '${_ARTIFACTORY_GROUP_ID}'
        version: '${_ARTIFACTORY_VERSION}'